AllCops:
  Exclude:
    - bin/**
    - app/assets/**/*
    - app/views/**/*
    - script/**/*
    - spec/**/*
    - public/**/*
    - config/**/*
    - db/**/*
    - doc/**/*
    - lib/**/*
    - vendor/**/*
    - provisioning/**/*
    - Gemfile
    - Rakefile
    - Guardfile

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
